export const stages = ['Abertura','Entendimento','Explicação','Direcionamento'];
export const situations = [
 {id:'preco',title:'Pediu preço e sumiu',hint:'Retome com contexto',icon:'price',question:'Oi! Sobre a proposta que conversamos, ficou alguma dúvida que eu possa esclarecer?',missing:'Revisar a necessidade, o histórico e se houve autorização para retomar o contato.',strategy:'Retome a proposta com uma pergunta útil, sem cobrar uma resposta.',step:'Entendimento',next:'Se houver uma dúvida, responda com dados confirmados. Se não houver interesse, respeite e encerre o acompanhamento.',page:55},
 {id:'caro',title:'Achou caro',hint:'Entenda antes de argumentar',icon:'coins',question:'Entendi. O valor ficou acima do que você planejava investir ou você está comparando com outra proposta?',missing:'O motivo da percepção de preço: orçamento, comparação ou valor ainda não percebido.',strategy:'Acolha a preocupação e investigue o motivo antes de defender o preço.',step:'Entendimento',next:'Se for comparação, pergunte o que a outra proposta inclui. Se for orçamento, confira as alternativas autorizadas antes de oferecer.',page:51},
 {id:'pensar',title:'Disse “vou pensar”',hint:'Descubra a dúvida real',icon:'thought',question:'Claro. O que você gostaria de avaliar melhor antes de decidir?',missing:'Qual dúvida, critério ou pessoa ainda influencia a decisão.',strategy:'Abra espaço para o cliente explicar o que precisa avaliar, sem apressá-lo.',step:'Entendimento',next:'Esclareça o ponto informado e pergunte se faz sentido combinar um retorno. Se preferir não continuar, respeite.',page:51},
 {id:'desconto',title:'Pediu desconto',hint:'Proteja o valor da solução',icon:'discount',question:'Entendi. O que mais pesa para você neste momento: o valor total ou a forma de pagamento?',missing:'A restrição real e quais condições a empresa efetivamente autoriza.',strategy:'Investigue a dificuldade e consulte a política antes de mencionar qualquer condição.',step:'Entendimento',next:'Confira a política da empresa. Se não houver condição autorizada, não prometa desconto nem parcelamento.',page:52},
 {id:'comparando',title:'Comparando opções',hint:'Ajude a comparar com clareza',icon:'users',question:'O que você está considerando mais importante para escolher entre as propostas?',missing:'Os critérios do cliente e o escopo das propostas comparadas.',strategy:'Entenda os critérios e compare apenas informações verificadas, sem desqualificar o concorrente.',step:'Entendimento',next:'Depois de identificar o critério, explique os diferenciais confirmados que realmente respondem a essa necessidade.',page:52},
 {id:'sumiu',title:'Não responde mais',hint:'Retome sem pressionar',icon:'clock',question:'Oi! Ainda faz sentido continuarmos essa conversa ou você prefere encerrar por enquanto?',missing:'O histórico, o motivo do contato e se existe um retorno combinado.',strategy:'Confirme se a necessidade continua atual. Não interprete silêncio como consentimento.',step:'Direcionamento',next:'Se quiser continuar, retome a necessidade. Se recusar ou pedir para parar, encerre. Não envie uma sequência automática.',page:55},
 {id:'inicio',title:'Iniciar uma conversa',hint:'Crie uma boa conexão',icon:'hello',question:'Olá! Que bom falar com você. O que você está buscando hoje?',missing:'A necessidade e o objetivo do cliente.',strategy:'Receba com naturalidade e faça uma pergunta aberta para iniciar o entendimento.',step:'Abertura',next:'Leia a resposta completa, confirme o que entendeu e faça uma pergunta por vez antes de recomendar.',page:17},
 {id:'outro',title:'Outra situação',hint:'Olhe para o contexto',icon:'other',question:'Para eu te orientar melhor, o que é mais importante resolver neste momento?',missing:'Identificar a necessidade, a dúvida principal e os fatos disponíveis.',strategy:'Esclareça a necessidade antes de apresentar argumentos ou promessas.',step:'Entendimento',next:'Use a informação recebida para escolher a próxima etapa. Se faltar um dado da empresa, confirme internamente.',page:28},
];
export type Company={name:string;services:string;differentials:string;prices:string;payment:string;deadlines:string;discount:string;nextAction:string};
export const emptyCompany:Company={name:'',services:'',differentials:'',prices:'',payment:'',deadlines:'',discount:'Descontos somente com autorização expressa do gestor.',nextAction:''};
export type Analysis={situation:string;stage:string;missing:string;strategy:string;response:string;nextStep:string;source:string;mode:string;id?:string};
export function guided(input:{situation:string;message:string;need?:string;moment?:string;tone?:string},company:Company):Analysis{
 const item=situations.find(x=>x.id===input.situation)||situations[7];
 const m=input.message.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const stop=/nao (quero|tenho interesse)|pare de|nao me (mande|envie|procure)|nao entre em contato|remova meu/.test(m);
 const complaint=/reclam|atras|defeito|nao recebi|insatisfeit|devolu/.test(m);
 const close=/quero (comprar|fechar|contratar)|como (compro|pago)|vamos fechar/.test(m);
 let response=item.question, stage=item.step, missing=item.missing,strategy=item.strategy,nextStep=item.next;
 if(stop){response='Entendido. Vou encerrar o acompanhamento por aqui. Obrigado por me avisar.';stage='Direcionamento';missing='Nenhuma informação adicional é necessária para respeitar a recusa.';strategy='Respeite a decisão e encerre o contato.';nextStep='Registre a recusa e não retome a abordagem comercial sem uma nova solicitação.';}
 else if(complaint){response='Sinto muito por essa experiência. Pode me contar o que aconteceu para eu entender e verificar como podemos resolver?';missing='Os fatos, o impacto e o que já foi tratado.';strategy='Acolha a reclamação e apure antes de prometer uma solução.';nextStep='Confirme os fatos e encaminhe ao responsável. Só informe prazos e soluções autorizados.';}
 else if(close){response=company.nextAction ? 'Vamos seguir. Posso te explicar o próximo passo para confirmar?' : 'Vamos seguir. Vou confirmar o procedimento para te orientar corretamente.';stage='Direcionamento';missing=company.nextAction?'Confirme se as condições apresentadas continuam válidas.':'O procedimento de confirmação da empresa.';strategy='Confirme internamente o procedimento e explique apenas o que está autorizado.';nextStep=company.nextAction||'Confirme internamente o procedimento, sem inventar links, datas ou condições.';}
 if(input.tone==='acolhedora'&&!stop&&!complaint)response='Obrigado por me contar. '+response.replace(/^Entendi\. /,'');
 if(input.tone==='curta'&&!stop&&!complaint&&!close)response=item.id==='caro'?'O valor ficou acima do seu orçamento ou de outra proposta?':item.question;
 return {situation:stop?'O cliente sinaliza que não quer continuar.':complaint?'A mensagem contém sinais de uma reclamação.':close?'O cliente sinaliza intenção de avançar.':`Situação selecionada: ${item.title.toLowerCase()}.`,stage,missing,strategy,response,nextStep,source:complaint?'Gestores · capítulo 24 · PDF p. 147':`Atendentes · PDF p. ${item.page}`,mode:'guided'};
}
export const trainingCases=[
 {title:'O preço virou uma objeção',message:'Achei muito caro. Na outra empresa me passaram mais barato.',focus:'Entendimento',tip:'Investigue o que está sendo comparado antes de justificar o preço.',reference:'Atendentes · capítulo 19 · PDF p. 51'},
 {title:'Uma decisão em aberto',message:'Gostei, mas vou pensar e depois te aviso.',focus:'Entendimento',tip:'Descubra o que falta avaliar e combine a continuidade com permissão.',reference:'Atendentes · capítulo 19 · PDF p. 51'},
 {title:'Desconto sem autorização',message:'Se você fizer 20% de desconto, eu fecho agora.',focus:'Entendimento',tip:'Não conceda condições que não foram autorizadas. Investigue a dificuldade.',reference:'Atendentes · capítulo 19 · PDF p. 52'},
 {title:'Primeiro contato',message:'Olá, queria saber mais sobre o serviço de vocês.',focus:'Abertura',tip:'Acolha e entenda o que a pessoa busca antes de explicar tudo.',reference:'Atendentes · capítulo 4 · PDF p. 17'},
 {title:'Respeitar o encerramento',message:'Não tenho interesse. Por favor, não me mande mais mensagens.',focus:'Direcionamento',tip:'Respeite a recusa, encerre com cuidado e não tente reabrir a venda.',reference:'Atendentes · capítulo 18 · PDF p. 49'}
];
