import { env } from 'cloudflare:workers';
import { database, identity, sameOrigin, userIdentity } from '@/lib/db';
import { emptyCompany } from '@/lib/method';
import { z } from 'zod';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const actor=await userIdentity(req),user=actor.id, db=database();const [company,analyses,practices]=await Promise.all([db.prepare('SELECT value FROM settings WHERE user_id=?').bind(user).first<{value:string}>(),db.prepare('SELECT * FROM analyses WHERE user_id=? ORDER BY created_at DESC LIMIT 500').bind(user).all(),db.prepare('SELECT * FROM practices WHERE user_id=? ORDER BY created_at DESC LIMIT 500').bind(user).all()]);return json({user:actor,company:company?JSON.parse(company.value):emptyCompany,analyses:analyses.results.map((x:any)=>({...x,result:JSON.parse(x.result)})),practices:practices.results.map((x:any)=>({...x,review:JSON.parse(x.review)})),ai:!!env.OPENAI_API_KEY});}catch(e){return json({error:(e as Error).message},401)}}
const companySchema=z.object({name:z.string().max(150),services:z.string().max(5000),differentials:z.string().max(3000),prices:z.string().max(3000),payment:z.string().max(2000),deadlines:z.string().max(2000),discount:z.string().max(2000),nextAction:z.string().max(2000)});
const updateSchema=z.object({id:z.string().max(100),favorite:z.boolean().optional(),copied:z.boolean().optional(),outcome:z.enum(['Em andamento','Venda concluída','Sem interesse','Sem resposta','Encerrado']).optional()});
export async function POST(req:Request){try{sameOrigin(req);const user=await identity(req),db=database();if(Number(req.headers.get('content-length')||0)>30000)return json({error:'Conteúdo muito longo.'},413);const b:any=await req.json();if(b.action==='company'){const c=companySchema.parse(b.value);await db.prepare('INSERT INTO settings(user_id,value) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET value=excluded.value').bind(user,JSON.stringify(c)).run();return json({ok:true});}if(b.action==='update'){const v=updateSchema.parse(b);const statements=[];if(v.favorite!==undefined)statements.push(db.prepare('UPDATE analyses SET favorite=? WHERE id=? AND user_id=?').bind(v.favorite?1:0,v.id,user));if(v.copied!==undefined)statements.push(db.prepare('UPDATE analyses SET copied=1 WHERE id=? AND user_id=?').bind(v.id,user));if(v.outcome)statements.push(db.prepare('UPDATE analyses SET outcome=? WHERE id=? AND user_id=?').bind(v.outcome,v.id,user));if(statements.length)await db.batch(statements);return json({ok:true});}return json({error:'Ação inválida.'},400);}catch(e){return json({error:e instanceof z.ZodError?'Revise os campos e seus limites.':(e as Error).message},400)}}
